######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 8 14:05:16 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lcrypto

# Input
SOURCES += test_rolling_hash.cc ../../rolling_hash.cc \
    ../../random.cc

HEADERS += \
    ../../random.hh
